### ISSUE TITLE
qx超话cookie路径与文件存放路径不匹配

### ISSUE THREAD

**Issue by wrong5210** [nzw9314/QuantumultX#10]
script应该为scripts
正确写法：
https:\/\/weibo\.com\/p\/aj\/general\/button\?ajwvr=6&api=http:\/\/i\.huati\.weibo\.com\/aj\/super\/checkin url script-request-header nzw9314/NavePnow/Scripts/weibo/get_cookie_qx.js

**Comment by nzw9314** [comment]
已修正
