### ISSUE TITLE
豆瓣证书错误

### ISSUE THREAD

**Issue by bbq191** [nzw9314/QuantumultX#103]
1. 打开豆瓣，偶尔会报证书错误。
2. 100%无法刷新列表。
3. 有私信提醒，打开后刷不出任何消息。

**Comment by nzw9314** [comment]
我这没有复现，看网络活动，确认下是分流还是脚本的原因

**Comment by lich13** [comment]
确定是Get_Cookie_Remote.conf导致的问题 只能手动关掉

**Comment by lich13** [comment]
> 我这没有复现，看网络活动，确认下是分流还是脚本的原因

确定是Get_Cookie_Remote.conf导致的问题 只能手动关掉

**Comment by nzw9314** [comment]
说明里有写
Cookie获取成功后在重写里禁用掉本订阅
Cookie失效时在重写里启用本订阅

可以在使用后手动将其禁用，以免产生不必要的MITM.

**Comment by bbq191** [comment]
原来如此，受教了
