### ISSUE TITLE
Get_Cookie_Remote.conf该更新了

### ISSUE THREAD

**Issue by MisterGlasses** [nzw9314/QuantumultX#124]
chavyleung大佬的cookie脚本中有百度签到的cookie脚本，大佬你的cookie脚本中却没有，望更新，多谢！

# 百度签到
^https?:\/\/tieba\.baidu\.com\/?.? url script-request-header chavyleung/tieba/tieba.cookie.js

**Comment by nzw9314** [comment]
已添加
