### ISSUE TITLE
boxjs地址变了

### ISSUE THREAD

**Issue by MisterGlasses** [nzw9314/QuantumultX#130]
hostname = 8.8.8.8

^https://8.8.8.8/api url script-request-body https://gitee.com/chavyleung/scripts/raw/master/chavy.box.js
^https://8.8.8.8/(home|sub|my|app|log|revert)($|\/) url script-response-body https://gitee.com/chavyleung/scripts/raw/master/chavy.box.js

**Comment by nzw9314** [comment]
已更换

**Comment by MisterGlasses** [comment]
又变了😬
