### ISSUE TITLE
请删除滴答清单pro的脚本，否则会导致滴答清单无法正常联网

### ISSUE THREAD

**Issue by coderloverXH** [nzw9314/QuantumultX#133]
请把 https://raw.githubusercontent.com/nzw9314/QuantumultX/master/Js.conf  链接里的下面这部分内容删除：

"
滴答清单 pro
^https:\/\/(ticktick|dida365)\.com\/api\/v2\/user\/status url script-response-body https://raw.githubusercontent.com/nzw9314/QuantumultX/master/NobyDa/QuantumultX/File/DiDaQingDan.js
"

原因：
1、如果不删除，会导致滴答清单无法正常联网

2、该脚本已经失效，原作者NobyDa大佬已经把他仓库里的NobyDa/QuantumultX/File/DiDaQingDan.js文件删除了

**Comment by nzw9314** [comment]
旧版可用5.2.51(832943581)
不想用该脚本可以用资源解析器排除
