### ISSUE TITLE
JS.conf导致打开bilibili时弹出收藏排行

### ISSUE THREAD

**Issue by MisterGlasses** [nzw9314/QuantumultX#134]
JS.conf导致打开bilibili时弹出收藏排行 不知道这是加的功能还是什么？
https://app.bilibili.com/x/v2/space\?access_key url script-response-body https://raw.githubusercontent.com/nzw9314/QuantumultX/master/Script/bilibili_space_qx.js
![AA4117B7-1255-4080-8000-42198CB36B41](https://user-images.githubusercontent.com/27768847/88460903-3a03c100-ced2-11ea-9727-fd661552a0ff.png)

**Comment by nzw9314** [comment]
可用资源解析器排除该脚本
