### ISSUE TITLE
重写规则可实现模拟手机百度ua

### ISSUE THREAD

**Issue by MisterGlasses** [nzw9314/QuantumultX#135]
![2EA661E1-C288-45A2-AE1E-25D95F8E23DA](https://user-images.githubusercontent.com/27768847/88471250-a1a12700-cf39-11ea-85a0-cd5c75e23efd.png)
已实测 无广告 没有下载app提示 跟手机百度效果一样 大佬你整合一下我就不用单独再新建订阅了
# 百度更换 UA
^https?:\/\/.*\.baidu\.com url request-header (\r\n)User-Agent:.+(\r\n) request-header $1User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Mobile/15E148 Safari/16C50 Quark/604.1 T7/10.3 SearchCraft/2.6.3 (Baidu; P1 8.0.0)$2

hostname = *.baidu.com

**Comment by nzw9314** [comment]
这个可以pr给eHpo 去广告规则
