### ISSUE TITLE
ipad photoshop卡在Loading your documents

### ISSUE THREAD

**Issue by CheYanShang** [nzw9314/QuantumultX#186]
Fake VIP:越南大佬的角本卡在loading your documents无法正常使用，有什么解决方案吗？

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by macro233** [comment]
Kohn ***@***.***>于2021年8月16日 周一上午12:52写道：

**Comment by Lorde627** [comment]
我也有相同的问题，你解决了吗？
