### ISSUE TITLE
163网易云音乐打开客户端频繁弹出写入cookie

### ISSUE THREAD

**Issue by liuleisail** [nzw9314/QuantumultX#25]
太频繁了，已经影响正常应用了，是不是有bug？

**Comment by githubdulong** [comment]
禁用获取cookie

发自我的iPhone

**Comment by nzw9314** [comment]
> 太频繁了，已经影响正常应用了，是不是有bug？

注意看README， 获取完Cookie，在QuantumultX重写订阅中 向右滑动禁用Cookie订阅，仅在失效或需要时打开该订阅

**Comment by liuleisail** [comment]
老大，重写订阅，引用中右划没有禁用啊？只有标签，删除和编辑。
在调试构造请求里面倒是有禁用，编辑和删除。
怎么找单独的 禁用？
请老大明示

发自我的iPhone

**Comment by liuleisail** [comment]
发自我的iPhone

**Comment by nzw9314** [comment]
> 老大，重写订阅，引用中右划没有禁用啊？只有标签，删除和编辑。 在调试构造请求里面倒是有禁用，编辑和删除。 怎么找单独的 禁用？ 请老大明示 发自我的iPhone
> […](#)

左右不分是怎么跑这提issue的

**Comment by liuleisail** [comment]
呃…确实，确实，哈，习惯思维了，感谢感谢！

发自我的iPhone
