### ISSUE TITLE
大佬,googlevideo又被你加到主机名了,油管会员打不开视频了

### ISSUE THREAD

**Issue by dampier2020** [nzw9314/QuantumultX#38]
https://raw.githubusercontent.com/nzw9314/QuantumultX/master/Js_local_WorkingCopy.conf.在这个里面,麻烦删删掉一下下

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by nzw9314** [comment]
已删除

**Comment by dampier2020** [comment]
这效率,不是盖的
