### ISSUE TITLE
Special.list 中的部分 URL-REGEX 规则会导致哔哩哔哩 APP 部分请求在进行规则匹配时耗时过长

### ISSUE THREAD

**Issue by Hyseen** [nzw9314/QuantumultX#39]
[Special.list](https://raw.githubusercontent.com/nzw9314/QuantumultX/master/Surge/Ruleset/Special.list) 中的部分 URL-REGEX 规则：
> URL-REGEX,(api|ps|sv|offnavi|newvector|ulog.imap|newloc)(.map|).(baidu|n.shifen).com
> URL-REGEX,(.+.|^)(360|so|qihoo|360safe|qhimg|360totalsecurity|yunpan).(cn|com)
> URL-REGEX,(.+.)?(torrent|announce.php?passkey=|tracker|BitTorrent|bt_key|ed2k|find_node|get_peers|info_hash|magnet:|peer_id=|sandai|Thunder|XLLiveUD|xunlei)(……+)?

会导致在开启 MitM 并将 `*.bilibili.com` 加入 hostname 后，哔哩哔哩 APP 部分请求（如首页 Feed、动态等）在规则匹配阶段时耗时过长

**Comment by nzw9314** [comment]
感谢反馈，已注释
