### ISSUE TITLE
想问下配置文件里面这种粗体是怎么弄的

### ISSUE THREAD

**Issue by oldzhg** [nzw9314/QuantumultX#43]
𝐏𝐫𝐨𝐱𝐲 = select, 𝐀𝐮𝐭𝐨, 𝐒𝐞𝐥𝐞𝐜𝐭, 𝐅𝐚𝐥𝐥𝐛𝐚𝐜𝐤
自己添加了其他的策略，但是没有上面的粗体效果

**Comment by nzw9314** [comment]
https://liuguogy.github.io/JSBox-addins/?q=show&objectId=5ceccaded5de2b00708724bb
JSBOX 里面的Patterns脚本
