### ISSUE TITLE
联通营业厅轮播广告，求大佬添加至wc.conf

### ISSUE THREAD

**Issue by Wangsc1** [nzw9314/QuantumultX#5]
/*
^https?://m\.client\.10010\.com/uniAdmsInterface/getHomePageAd url script-response-body china_unicom.js

hostname=m.client.10010.com
*/

const url = $request.url
var body = $response.body
const path1 = "/uniAdmsInterface/getHomePageAd"
if (url.indexOf(path1) != -1) {
    let obj = JSON.parse(body);
    if (obj.diffNetCard_A7) obj.diffNetCard_A7 = [];
    obj.homeAdv_A5.advCntList = [];
    body = JSON.stringify(obj);
    $done({ body });
}

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by nzw9314** [comment]
已添加。感谢🙏

**Comment by Wangsc1** [comment]
谢谢
