### ISSUE TITLE
招行信用卡公众号签到失败

### ISSUE THREAD

**Issue by MapleSpirit** [nzw9314/QuantumultX#57]
`[JS Console]: {"respCode":"2001","respMsg":"非法token"}`
头一天获取过cookie后，到了第二天自动触发签到时总是签到失败，查日志显示这个，不清楚是什么原因

**Comment by nzw9314** [comment]
Cookie存活时间只有一天，建议弃坑

**Comment by fyrs3101** [comment]
这个我问了，没有办法，他这个小饼干确实存活的太短了，没劲
