### ISSUE TITLE
netflix获取评分的正则更新

### ISSUE THREAD

**Issue by Wangsc1** [nzw9314/QuantumultX#6]
第一条很长的正则还是老的，yichahucha已经更新了,hostname少了com,
![DEFD9423-0BBB-4A0E-8C37-C629BA3500F4](https://user-images.githubusercontent.com/26079238/73133703-752e5000-4067-11ea-90b5-850d09b72252.jpeg)
![5EAA5352-A86F-4C22-877F-917B35CAEB1F](https://user-images.githubusercontent.com/26079238/73133704-752e5000-4067-11ea-9f5f-3495e911f31e.jpeg)
![F0C95D5D-169E-4B39-B153-6F94F4D7F8CF](https://user-images.githubusercontent.com/26079238/73133676-27194c80-4067-11ea-9215-789e28c122aa.jpeg)

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by nzw9314** [comment]
> 第一条很长的正则还是老的，yichahucha已经更新了,hostname少了com,
> ![DEFD9423-0BBB-4A0E-8C37-C629BA3500F4](https://user-images.githubusercontent.com/26079238/73133703-752e5000-4067-11ea-90b5-850d09b72252.jpeg)
> ![5EAA5352-A86F-4C22-877F-917B35CAEB1F](https://user-images.githubusercontent.com/26079238/73133704-752e5000-4067-11ea-9f5f-3495e911f31e.jpeg)
> ![F0C95D5D-169E-4B39-B153-6F94F4D7F8CF](https://user-images.githubusercontent.com/26079238/73133676-27194c80-4067-11ea-9215-789e28c122aa.jpeg)
> 
> Sent from [PPHub](https://apps.apple.com/cn/app/id1314212521)

**Comment by nzw9314** [comment]
已修正。感谢🙏

**Comment by Wangsc1** [comment]
谢谢，感谢大佬收集的这么全
