### ISSUE TITLE
小小影视iOS最新tf版去视频开头XX秒广告失败

### ISSUE THREAD

**Issue by lxk0301** [nzw9314/QuantumultX#62]
### 下载链接 https://xiaoxiaoys1.com/

![image](https://user-images.githubusercontent.com/21308593/81539327-ab87a500-93a2-11ea-85b8-a5c67bac3d72.png)

**Comment by nzw9314** [comment]
经测试 最新TF版无广告 脚本未失效

**Comment by lxk0301** [comment]
难道是我下载错了嘛

**Comment by lxk0301** [comment]
这是我目前手机端的tf版
![image](https://user-images.githubusercontent.com/21308593/81544668-65364400-93aa-11ea-8df8-1e4267bea133.png)

**Comment by nzw9314** [comment]
我刚测试的就是这个版本

# > 小小影视 Qx版
# 会员
https:\/\/.*.xiaoxiao(img|apps|appxs).com url request-header (\r\n)Cookie:.+(\r\n) request-header $1Cookie: xxx_api_auth=6131333537653261363463323331666265663763396239663835636662373930$2
# 去广告
https:\/\/.*\/getGlobalData url script-response-body https://raw.githubusercontent.com/Alex0510/Eric/master/surge/Script/xxysad.js

hostname = *.xiaoxiao*.com
