### ISSUE TITLE
微信小程序-活动抽奖Token失效无法获取

### ISSUE THREAD

**Issue by longgegeaixuexi** [nzw9314/QuantumultX#72]
作者你好，这两天我微信小程序-活动抽奖无法签到，提示Token失效需要重新获取，但是我重新获取没有反应。用Loon测试是第一次写入Token成功，但是一运行就和这一样的提示，并且也无法再获取Token。
![2BB31258-4F65-4C5B-B9F4-158A6F0C73AC](https://user-images.githubusercontent.com/34785901/84757713-0d1cde00-aff7-11ea-8448-476bdae8da1c.png)

**Comment by HarveyCZ** [comment]
我的也是这样的，貌似获取不了cookie了，尝试多种方式都没有办法获取

**Comment by nzw9314** [comment]
弃坑
