### ISSUE TITLE
关于最新cookie同步问题

### ISSUE THREAD

**Issue by windy1lee** [nzw9314/QuantumultX#8]
同步时出现错误，应该是商店版与tf版的header和body的问题！
##QX1.06 TF195及以后版本
^https:\/\/c\.m\.163\.com\/uc\/api\/sign\/v2\/commit url script-request-body nzw9314/chavyleung/neteasenews/neteasenews.cookie.js
主要是这个的问题，建议单独留一个商店版使用的！或者商店和tf出现差异时前面加上分号

**Comment by nzw9314** [comment]
行吧 我那我单独开一个QX1.06 TF195及以后版本的cookie
